name: skdocstool
version: '$version'
author: Crebs
main: org.skdocs.skdocstool.Skdocstool
api-version: '1.21.11'
load: POSTWORLD

commands:
  gendocs:
    description: Generate documentation for your project.
    usage: /gendocs
    permission: skdocstool.gendocs
    permission-message: You do not have permission to use this command.
  docs:
    description: Preview addon documentation.
    usage: /docs preview <addon_name>
    permission: skdocstool.docspreview
    permission-message: You do not have permission to use this command.
